services:
  # Servicio del Backend (API)
  server:
    build: ./server
    container_name: todo-pwa-api
    restart: unless-stopped
    env_file:
      - ./.env # Carga las variables desde el archivo .env
    ports:
      # Exponemos el puerto 5000 para poder probar la API directamente si queremos
      - "5000:5000"
    networks:
      - app-network

  # Servicio del Frontend (Cliente)
  customer:
    build: ./customer
    container_name: todo-pwa-client
    restart: unless-stopped
    ports:
      # Mapeamos el puerto 80 del contenedor al puerto 80 de nuestra máquina
      - "80:80"
    networks:
      - app-network
    depends_on:
      - server # Le decimos que espere a que el backend inicie

# Docker creará una red para que los contenedores se comuniquen por su nombre
networks:
  app-network:
    driver: bridge