services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: todo-pwa-api
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    networks:
      - app-network

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile.prod
    container_name: todo-pwa-client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge