services:
  # Servicio del Backend para Desarrollo
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: todo-pwa-api-dev
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules

  # Servicio del Frontend para Desarrollo
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile.dev # Usa el Dockerfile de desarrollo
    container_name: todo-pwa-client-dev
    ports:
      - "3000:3000" # Vite corre en el puerto 5173
    networks:
      - app-network
    depends_on:
      - server
    volumes:
      - ./customer:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge