services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: todo-pwa-api
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile.prod
    container_name: todo-pwa-client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - server
    # volumes:
    #   - ./customer:/app
    #   - /app/node_modules

networks:
  app-network:
    driver: bridge