services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: todo-pwa-api
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules
    # El comando se puede quitar, ya que está en el Dockerfile.dev
    # command: npm run dev 

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile.dev
    container_name: todo-pwa-client
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - server
    volumes:
      - ./customer:/app
      - /app/node_modules
    # El comando se puede quitar, ya que está en el Dockerfile.dev
    # command: npm run dev

networks:
  app-network:
    driver: bridge