# Usamos la imagen completa de Node
FROM node:20

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos solo los package.json para aprovechar la caché de Docker
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Copiamos el resto del código
COPY . .

# Exponemos el puerto
EXPOSE 5000

# Comando final y robusto que se ejecuta al iniciar
CMD ["npm", "run", "dev"]