# Usamos la imagen completa de Node para tener todas las herramientas
FROM node:20

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos package.json para instalar dependencias
COPY package*.json ./

# Instalamos TODAS las dependencias, incluyendo las de desarrollo
RUN npm install

# Copiamos el resto del código
COPY . .

# Exponemos el puerto
EXPOSE 5000

# El comando por defecto se manejará desde docker-compose.yml
# Usamos npx para asegurarnos de que se ejecute la versión de nodemon
# instalada en node_modules, solucionando problemas de PATH.
CMD [ "npx", "nodemon", "src/server.ts" ]